In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

In [3]:
# calculate the mean of the array
mean = np.mean(arr)

print(mean)  # output: 3.0

3.0


In [4]:
# calculate the standard deviation of the array
std_dev = np.std(arr)

print(std_dev)  # output: 1.41421356

1.4142135623730951


In [5]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

In [6]:
# perform element-wise addition, subtraction, multiplication, and division of the two arrays
addition = np.add(arr1, arr2)
subtraction = np.subtract(arr1, arr2)
multiplication = np.multiply(arr1, arr2)
division = np.divide(arr1, arr2)

print(addition)      # output: [ 7  9 11 13 15]
print(subtraction)   # output: [-5 -5 -5 -5 -5]
print(multiplication) # output: [ 6 14 24 36 50]
print(division)       # output: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [7]:
# compute the dot product of the two arrays
dot_product = np.dot(arr1, arr2)

print(dot_product)

130


In [8]:
# generate a sequence of numbers within a range
seq = np.arange(1, 11)

print(seq)

[ 1  2  3  4  5  6  7  8  9 10]
